### ISSUE TITLE
关于 win-on-linux 的 _dev 镜像变体如何使用

### ISSUE THREAD

**Issue by kainy** [kkocdko/kblog#11]
https://kkocdko.site/post/202208221154

dev版本的和普通版本的crc32值怎么会一样呢？从百度网盘下载的dev启动不了哦 。。

**Comment by kkocdko** [comment]
_dev 是普通版叠加上的一层 snapshot，我确实文章里没写，大概就是要两个文件放一起然后把 hda 设置成 _dev 的。
