### ISSUE TITLE
已start，README能否加一个部署指南。

### ISSUE THREAD

**Issue by Byc4i** [kkocdko/kblog#5]
已start，README能否加一个部署指南。

**Comment by kkocdko** [comment]
这……按照常规方式就行了啊，不用写吧？

```
npm i
npm run serve
```

生成的内容在 `public` 文件夹

**Comment by Byc4i** [comment]
就是☺网站部署，比如docker pull一个镜像，run起来就是网站，xxx是主页，xxx链接是编辑文章的后台

**Comment by kkocdko** [comment]
这是静态博客，不是 WordPress。。。没必要，如果想要国内访问流畅那买个腾讯云的静态托管就好了。
