### ISSUE TITLE
About your past work on Youdao Dict

### ISSUE THREAD

**Issue by FionViber** [kkocdko/kblog#6]
Hi,

I am working on a project relates to Youdao Dict, and your modified version is the best I found. I really appreciate your modify instruction, and can I please ask to get your modified version? I am trying to adjust the default settings after installing.

**Comment by kkocdko** [comment]
Thanks for your support. But sorry, my local archive of Youdao Dict was lost.

About the modify of default settings, in my memory, I just wrote a batch file to redirect some environment variables like `%UserProfile%`, and pack them together. If you don't like this, maybe decompile the main executable and change the data path logic is a better (but complex) solution.

**Comment by FISHandCHEAP** [comment]
The problem is I don't know where's the setting files. I checked folders in Youdao's path and User, and nothing found. I can just repack the modified version by making a new installation exe if I can find the setting files.

**Comment by kkocdko** [comment]
It's in `%UserProfile%\AppData\ (one of three folders) \ Youdao (maybe)`.

The `%UserProfile%` is an env variable which directed to current user's profile dir.

**Comment by kkocdko** [comment]
Maybe changed? Or you can use [Sandboxie](https://github.com/sandboxie-plus/Sandboxie) to track it.
