### ISSUE TITLE
借鉴kblog的奇技淫巧

### ISSUE THREAD

**Issue by Meekdai** [kkocdko/kblog#8]
@kkocdko 大佬你好。
我前不久弄了个博客框架[Gmeek](https://github.com/Meekdai/Gmeek)是基于github issues，发现自己弄的还是不够轻量化。今天在V2EX看见了你的回复，[我如何将博客首页体积降至 3 KB](https://kkocdko.site/post/202106180833) 看了这篇博文，大受启发，决定学习借鉴一下你的博客，但是我不会nodejs，只会点python，不知道从何开始。所以前来询问一下思路，谢谢！

**Comment by kkocdko** [comment]
抱歉可能漏掉了邮件。入门不难的，这里没什么特定的建议，博客嘛，重要的是内容，至于技术方面用自己熟悉的就行了。
